import type {
  AbilityTier,
  ClanDef,
  ClanId,
  PowerDef,
  PowerId,
  Rank,
  Rarity,
  Stats,
  StatUpgrades,
  UniqueAbility,
} from "./types";
import { ABILITY_TIERS, RANKS, RARITIES } from "./types";

export const POWER_DEFS: Record<PowerId, PowerDef> = {
  fire: {
    id: "fire",
    name: "Fire",
    blurb: "Consuming heat and explosive force.",
    color: "#e85d3a",
    glow: "#ff8a5c",
    tags: ["elemental", "offense", "heat"],
    style: "nova",
    adj: "Infernal",
    noun: "Blaze",
    art: "Art",
    atk: 4,
    def: 0,
    spd: 1,
    hp: 0,
    energy: 0,
    crit: 1,
  },
  ice: {
    id: "ice",
    name: "Ice",
    blurb: "Stillness, freeze, and brittle edges.",
    color: "#7ec8e3",
    glow: "#c4f0ff",
    tags: ["elemental", "control", "cold"],
    style: "zone",
    adj: "Frozen",
    noun: "Glacier",
    art: "Domain",
    atk: 2,
    def: 2,
    spd: -1,
    hp: 2,
    energy: 1,
    crit: 0,
  },
  lightning: {
    id: "lightning",
    name: "Lightning",
    blurb: "Instant strikes that chain through foes.",
    color: "#d6c86a",
    glow: "#fff4a8",
    tags: ["elemental", "offense", "speed"],
    style: "beam",
    adj: "Storm",
    noun: "Bolt",
    art: "Flash",
    atk: 3,
    def: -1,
    spd: 4,
    hp: -2,
    energy: 1,
    crit: 3,
  },
  shadow: {
    id: "shadow",
    name: "Shadow",
    blurb: "Silence, ambush, and unseen edges.",
    color: "#5b6578",
    glow: "#9aa7c2",
    tags: ["dark", "speed", "stealth"],
    style: "dashStrike",
    adj: "Umbral",
    noun: "Veil",
    art: "Step",
    atk: 2,
    def: 0,
    spd: 4,
    hp: -1,
    energy: 0,
    crit: 4,
  },
  wind: {
    id: "wind",
    name: "Wind",
    blurb: "Cut and carry — speed made sharp.",
    color: "#a8c4b0",
    glow: "#d7f0de",
    tags: ["elemental", "speed", "control"],
    style: "cone",
    adj: "Gale",
    noun: "Tempest",
    art: "Dance",
    atk: 1,
    def: 0,
    spd: 5,
    hp: 0,
    energy: 1,
    crit: 2,
  },
  earth: {
    id: "earth",
    name: "Earth",
    blurb: "Weight, armor, and crushing force.",
    color: "#a9845a",
    glow: "#d4b48a",
    tags: ["elemental", "defense", "control"],
    style: "nova",
    adj: "Titan",
    noun: "Core",
    art: "Guard",
    atk: 2,
    def: 5,
    spd: -2,
    hp: 6,
    energy: 0,
    crit: 0,
  },
  water: {
    id: "water",
    name: "Water",
    blurb: "Flow, pressure, and relentless tide.",
    color: "#5b8fb8",
    glow: "#9cc8ea",
    tags: ["elemental", "control", "spirit"],
    style: "projectile",
    adj: "Tidal",
    noun: "Current",
    art: "Flow",
    atk: 1,
    def: 1,
    spd: 1,
    hp: 2,
    energy: 3,
    crit: 0,
  },
  blood: {
    id: "blood",
    name: "Blood",
    blurb: "Life taken and returned as hunger.",
    color: "#a33b3b",
    glow: "#e07070",
    tags: ["dark", "offense", "life"],
    style: "curse",
    adj: "Crimson",
    noun: "Pact",
    art: "Rite",
    atk: 4,
    def: -1,
    spd: 1,
    hp: 3,
    energy: -1,
    crit: 2,
  },
  spirit: {
    id: "spirit",
    name: "Spirit",
    blurb: "Wards, wisps, and borrowed life.",
    color: "#c9d4c4",
    glow: "#eef6ea",
    tags: ["spirit", "support", "light"],
    style: "pulse",
    adj: "Sacred",
    noun: "Wisp",
    art: "Hymn",
    atk: 0,
    def: 2,
    spd: 0,
    hp: 2,
    energy: 6,
    crit: 0,
  },
  time: {
    id: "time",
    name: "Time",
    blurb: "Delay, rewind, and stolen moments.",
    color: "#b8a46a",
    glow: "#ead9a0",
    tags: ["rare", "control", "spirit"],
    style: "zone",
    adj: "Chrono",
    noun: "Epoch",
    art: "Lock",
    atk: 2,
    def: 1,
    spd: 2,
    hp: 0,
    energy: 3,
    crit: 1,
  },
  void: {
    id: "void",
    name: "Void",
    blurb: "Absence given teeth.",
    color: "#6a6e7a",
    glow: "#c5c9d6",
    tags: ["rare", "dark", "offense"],
    style: "curse",
    adj: "Null",
    noun: "Eclipse",
    art: "Rift",
    atk: 5,
    def: 0,
    spd: 1,
    hp: -2,
    energy: 2,
    crit: 2,
  },
  light: {
    id: "light",
    name: "Light",
    blurb: "Judgment made visible.",
    color: "#e6e0c8",
    glow: "#fff8dc",
    tags: ["light", "offense", "spirit"],
    style: "beam",
    adj: "Radiant",
    noun: "Halo",
    art: "Judgment",
    atk: 3,
    def: 1,
    spd: 1,
    hp: 1,
    energy: 2,
    crit: 1,
  },
  dragon: {
    id: "dragon",
    name: "Dragon",
    blurb: "Ancient scale and cataclysm breath.",
    color: "#c45c4a",
    glow: "#f0a090",
    tags: ["rare", "offense", "beast"],
    style: "cone",
    adj: "Draconic",
    noun: "Wyrm",
    art: "Cataclysm",
    atk: 6,
    def: 2,
    spd: -1,
    hp: 4,
    energy: 1,
    crit: 1,
  },
  demon: {
    id: "demon",
    name: "Demon",
    blurb: "Berserk pacts and cruel strength.",
    color: "#8a3030",
    glow: "#d06060",
    tags: ["dark", "offense", "beast"],
    style: "dashStrike",
    adj: "Abyssal",
    noun: "Fiend",
    art: "Pact",
    atk: 6,
    def: -1,
    spd: 2,
    hp: 1,
    energy: 0,
    crit: 3,
  },
  gravity: {
    id: "gravity",
    name: "Gravity",
    blurb: "Pull, crush, and unmake footing.",
    color: "#7a7a88",
    glow: "#b8b8c8",
    tags: ["rare", "control", "defense"],
    style: "zone",
    adj: "Heavy",
    noun: "Singularity",
    art: "Bind",
    atk: 3,
    def: 3,
    spd: -2,
    hp: 3,
    energy: 2,
    crit: 0,
  },
  illusion: {
    id: "illusion",
    name: "Illusion",
    blurb: "False steps and broken certainty.",
    color: "#8a9aa8",
    glow: "#c5d4e0",
    tags: ["control", "stealth", "spirit"],
    style: "pulse",
    adj: "Phantom",
    noun: "Mirage",
    art: "Veil",
    atk: 1,
    def: 0,
    spd: 3,
    hp: 0,
    energy: 3,
    crit: 4,
  },
};

export const CLAN_DEFS: Record<ClanId, ClanDef> = {
  dragon: {
    id: "dragon",
    name: "Dragon Clan",
    epithet: "Scaleborn",
    blurb: "Heirs of the first flame. They strike like falling stars.",
    color: "#c45c4a",
    accent: "#e8a090",
    aura: "#c45c4a",
    bonuses: ["High Attack", "Fire resistance", "Dragon-aspected arts"],
    stats: { atk: 8, hp: 12, def: 4, crit: 2 },
  },
  shadow: {
    id: "shadow",
    name: "Shadow Clan",
    epithet: "Nightblade",
    blurb: "They move between heartbeats. A cut you never saw coming.",
    color: "#6a7384",
    accent: "#c5cedb",
    aura: "#8a96aa",
    bonuses: ["High Speed", "Critical damage", "Stealth arts"],
    stats: { spd: 18, crit: 8, atk: 4, hp: -6 },
  },
  spirit: {
    id: "spirit",
    name: "Spirit Clan",
    epithet: "Wardsinger",
    blurb: "Keepers of the inner flame. They outlast what they cannot crush.",
    color: "#c9d4c4",
    accent: "#eef4ea",
    aura: "#d5e0d0",
    bonuses: ["High Energy", "Healing pulse", "Wisp companions"],
    stats: { energy: 28, hp: 10, def: 4, atk: -2 },
  },
  demon: {
    id: "demon",
    name: "Demon Clan",
    epithet: "Oathbreaker",
    blurb: "Pact-bound berserkers. Pain is a language they speak fluently.",
    color: "#8a3030",
    accent: "#d07070",
    aura: "#a04040",
    bonuses: ["High Attack", "Berserk below 40% HP", "Lifesteal on heavy"],
    stats: { atk: 10, crit: 4, hp: 6, def: -2 },
  },
  celestial: {
    id: "celestial",
    name: "Celestial Clan",
    epithet: "Starwrought",
    blurb: "Balanced as the night sky. Light that does not blink.",
    color: "#dce3ea",
    accent: "#f4f7fa",
    aura: "#d0d8e0",
    bonuses: ["Balanced stats", "Light-aspected arts", "Stable growth"],
    stats: { hp: 8, energy: 10, atk: 4, def: 4, spd: 4, crit: 2 },
  },
  storm: {
    id: "storm",
    name: "Storm Clan",
    epithet: "Skybreaker",
    blurb: "Born under split clouds. They arrive as thunder arrives.",
    color: "#c8c070",
    accent: "#efe9b0",
    aura: "#d8d080",
    bonuses: ["High Speed", "Chain bonus on specials", "Dash recovery"],
    stats: { spd: 14, energy: 10, atk: 5, crit: 3 },
  },
  abyss: {
    id: "abyss",
    name: "Abyss Clan",
    epithet: "Deepborn",
    blurb: "From the lightless trench. Gravity and hunger in equal measure.",
    color: "#5a6570",
    accent: "#a8b4be",
    aura: "#6a7884",
    bonuses: ["High Defense", "Void resistance", "Pull on ultimate"],
    stats: { def: 8, hp: 14, atk: 3, energy: 6, spd: -4 },
  },
};

export interface NamedRecipe {
  name: string;
  type: string;
  element: string;
  rarity: Rarity;
  description: string;
}

export const RECIPES: Record<string, NamedRecipe> = {
  "fire+lightning+wind": {
    name: "Storm Inferno",
    type: "Cataclysm",
    element: "Stormfire",
    rarity: "Legendary",
    description: "A cyclone of burning lightning that scours the field.",
  },
  "blood+demon+shadow": {
    name: "Abyssal Blood Art",
    type: "Curse",
    element: "Abyss",
    rarity: "Mythic",
    description: "A pact that drinks life and returns it as night.",
  },
  "ice+spirit+time": {
    name: "Frozen Time Domain",
    type: "Domain",
    element: "Chronofrost",
    rarity: "Mythic",
    description: "A still world where only you may move.",
  },
  "dragon+fire+gravity": {
    name: "Draconic Cataclysm",
    type: "Breath",
    element: "Starfire",
    rarity: "Divine",
    description: "The sky folds. A wyrm of collapsing suns answers.",
  },
  "shadow+time+void": {
    name: "Eternal Eclipse",
    type: "Rift",
    element: "Voidnight",
    rarity: "Divine",
    description: "Light is postponed. The cut arrives from yesterday.",
  },
  "light+spirit+time": {
    name: "Celestial Chronoshift",
    type: "Miracle",
    element: "Starlight",
    rarity: "Mythic",
    description: "A hymn that rewinds wounds and judges the rest.",
  },
  "ice+water+wind": {
    name: "Glacial Tempest",
    type: "Storm",
    element: "Frostwind",
    rarity: "Epic",
    description: "Needles of ice riding a killing gale.",
  },
  "dragon+earth+gravity": {
    name: "Titan's Core",
    type: "Crush",
    element: "Worldstone",
    rarity: "Legendary",
    description: "The ground remembers it was once a throat.",
  },
  "illusion+shadow+spirit": {
    name: "Phantom Veil",
    type: "Mirage",
    element: "Ghostlight",
    rarity: "Epic",
    description: "You are everywhere the eye refuses to rest.",
  },
  "blood+time+void": {
    name: "Crimson Epoch",
    type: "Curse",
    element: "Bloodtime",
    rarity: "Divine",
    description: "History bleeds. You write the next hour in it.",
  },
  "demon+fire+lightning": {
    name: "Hellstorm Pact",
    type: "Cataclysm",
    element: "Hellfire",
    rarity: "Legendary",
    description: "A contract signed in thunder and cinder.",
  },
  "dragon+fire+light": {
    name: "Solar Wyrm",
    type: "Breath",
    element: "Sunscale",
    rarity: "Mythic",
    description: "Dawn given a spine and a hunger.",
  },
  "earth+gravity+void": {
    name: "Singularity Bind",
    type: "Bind",
    element: "Nullmass",
    rarity: "Mythic",
    description: "A point that refuses to share space.",
  },
  "light+spirit+wind": {
    name: "Heaven's Gale",
    type: "Storm",
    element: "Aether",
    rarity: "Epic",
    description: "A wind that carries judgment instead of dust.",
  },
  "ice+shadow+void": {
    name: "Absolute Zero",
    type: "Domain",
    element: "Nullfrost",
    rarity: "Divine",
    description: "Motion itself is found guilty.",
  },
  "blood+spirit+water": {
    name: "Tide of Souls",
    type: "Rite",
    element: "Soulwater",
    rarity: "Legendary",
    description: "The river remembers every name it has taken.",
  },
  "lightning+time+void": {
    name: "Chrono Bolt",
    type: "Flash",
    element: "Timearc",
    rarity: "Mythic",
    description: "The strike lands before the decision to throw it.",
  },
  "demon+dragon+void": {
    name: "Apocalypse Crown",
    type: "Cataclysm",
    element: "Endscale",
    rarity: "Transcendent",
    description: "Two thrones, one absence. The world kneels.",
  },
  "fire+ice+lightning": {
    name: "Primordial Triad",
    type: "Origin",
    element: "Firststorm",
    rarity: "Legendary",
    description: "The three first tongues of the world, spoken at once.",
  },
  "illusion+light+time": {
    name: "Mirage Eternity",
    type: "Mirage",
    element: "Falsedawn",
    rarity: "Mythic",
    description: "A forever that never quite arrives.",
  },
  "gravity+lightning+wind": {
    name: "Storm Anchor",
    type: "Bind",
    element: "Thundermass",
    rarity: "Epic",
    description: "Lightning nailed to the ground until it screams.",
  },
  "dragon+earth+fire": {
    name: "Magma Sovereign",
    type: "Breath",
    element: "Magma",
    rarity: "Legendary",
    description: "A crown of cooling stone and living heat.",
  },
  "demon+illusion+shadow": {
    name: "Nightmare King",
    type: "Curse",
    element: "Dread",
    rarity: "Mythic",
    description: "Fear given a court and a knife.",
  },
  "light+spirit+water": {
    name: "Sacred Spring",
    type: "Miracle",
    element: "Holywater",
    rarity: "Epic",
    description: "A well that mends what the war unmade.",
  },
  "blood+demon+fire": {
    name: "Infernal Offering",
    type: "Rite",
    element: "Bloodfire",
    rarity: "Legendary",
    description: "You burn the cost and keep the change.",
  },
  "gravity+time+void": {
    name: "Event Horizon",
    type: "Rift",
    element: "Endtime",
    rarity: "Transcendent",
    description: "A door that only opens inward.",
  },
  "illusion+shadow+wind": {
    name: "Silent Gale",
    type: "Step",
    element: "Whisperwind",
    rarity: "Rare",
    description: "A cut that arrives as weather.",
  },
  "ice+spirit+water": {
    name: "Frost Soul",
    type: "Domain",
    element: "Soulice",
    rarity: "Epic",
    description: "A heart that will not thaw for anyone.",
  },
  "dragon+lightning+wind": {
    name: "Thunder Wyrm",
    type: "Breath",
    element: "Skybolt",
    rarity: "Legendary",
    description: "Wings of thunder. Teeth of the cloudline.",
  },
  "light+spirit+void": {
    name: "Duality Gate",
    type: "Rift",
    element: "Twilight",
    rarity: "Divine",
    description: "Two laws, one threshold. You are the hinge.",
  },
  "earth+water+wind": {
    name: "Nature's Wrath",
    type: "Storm",
    element: "Wild",
    rarity: "Rare",
    description: "The old world remembering how to bite.",
  },
  "blood+shadow+time": {
    name: "Night of Blades",
    type: "Art",
    element: "Bloodnight",
    rarity: "Legendary",
    description: "Every second grows an edge.",
  },
  "demon+earth+gravity": {
    name: "Abyssal Crush",
    type: "Crush",
    element: "Hellstone",
    rarity: "Epic",
    description: "The floor rises to meet the proud.",
  },
  "dragon+fire+wind": {
    name: "Skyfire Breath",
    type: "Breath",
    element: "Skyfire",
    rarity: "Legendary",
    description: "Horizon to horizon, a single exhale.",
  },
  "gravity+ice+void": {
    name: "Frozen Prison",
    type: "Bind",
    element: "Nullice",
    rarity: "Mythic",
    description: "A cell whose walls are the idea of cold.",
  },
  "demon+spirit+void": {
    name: "Soul Reaver",
    type: "Curse",
    element: "Soulvoid",
    rarity: "Divine",
    description: "What leaves the body does not leave you.",
  },
  "light+lightning+time": {
    name: "Divine Spark",
    type: "Flash",
    element: "Godarc",
    rarity: "Mythic",
    description: "A moment of creation, aimed.",
  },
  "gravity+void+water": {
    name: "Drowning Star",
    type: "Rift",
    element: "Darktide",
    rarity: "Mythic",
    description: "A sun that learned to sink.",
  },
  "blood+illusion+spirit": {
    name: "Crimson Phantom",
    type: "Mirage",
    element: "Bloodwisp",
    rarity: "Epic",
    description: "A wound that walks without its owner.",
  },
  "dragon+ice+time": {
    name: "Frozen Wyrm Age",
    type: "Domain",
    element: "Glacierwyrm",
    rarity: "Divine",
    description: "An era of ice with a dragon for a calendar.",
  },
  "earth+fire+lightning": {
    name: "Volcanic Arc",
    type: "Cataclysm",
    element: "Magmaarc",
    rarity: "Epic",
    description: "Stone split by a thought of thunder.",
  },
  "illusion+time+void": {
    name: "Unwritten Hour",
    type: "Rift",
    element: "Neverwhen",
    rarity: "Divine",
    description: "A minute that refuses to have happened.",
  },
  "blood+dragon+fire": {
    name: "Heart of Cinder",
    type: "Breath",
    element: "Bloodcinder",
    rarity: "Legendary",
    description: "A pulse that ignites whatever it loves.",
  },
  "light+shadow+void": {
    name: "Umbral Radiance",
    type: "Judgment",
    element: "Eclipse",
    rarity: "Mythic",
    description: "Light that learned the manners of night.",
  },
  "demon+gravity+void": {
    name: "Throne of Collapse",
    type: "Crush",
    element: "Abyss",
    rarity: "Transcendent",
    description: "A seat made of everything that failed to stand.",
  },
  "spirit+time+wind": {
    name: "Breath of Ages",
    type: "Hymn",
    element: "Aetherwind",
    rarity: "Epic",
    description: "A wind that has already forgiven you.",
  },
  "earth+ice+water": {
    name: "Worldveil Frost",
    type: "Guard",
    element: "Permafrost",
    rarity: "Rare",
    description: "A continent deciding to close.",
  },
  "lightning+shadow+wind": {
    name: "Black Tempest",
    type: "Storm",
    element: "Nightbolt",
    rarity: "Epic",
    description: "Thunder without a sky to claim it.",
  },
  "dragon+light+spirit": {
    name: "Saint Wyrm",
    type: "Miracle",
    element: "Holyscale",
    rarity: "Mythic",
    description: "A dragon that kept its first promise.",
  },
  "blood+illusion+shadow": {
    name: "Red Masquerade",
    type: "Art",
    element: "Crimsonveil",
    rarity: "Epic",
    description: "Every face in the dark is yours.",
  },
};

export const AFFINITY: Record<string, number> = {
  "fire+lightning": 18,
  "fire+wind": 16,
  "fire+dragon": 22,
  "fire+demon": 18,
  "ice+water": 18,
  "ice+time": 20,
  "ice+wind": 12,
  "lightning+wind": 18,
  "lightning+time": 16,
  "lightning+light": 14,
  "shadow+void": 22,
  "blood+shadow": 18,
  "illusion+shadow": 18,
  "demon+shadow": 16,
  "spirit+wind": 12,
  "earth+gravity": 20,
  "dragon+earth": 16,
  "earth+water": 10,
  "spirit+water": 14,
  "blood+water": 10,
  "blood+demon": 22,
  "blood+time": 14,
  "light+spirit": 18,
  "spirit+time": 16,
  "time+void": 24,
  "gravity+void": 20,
  "demon+void": 18,
  "light+time": 14,
  "light+lightning": 12,
  "dragon+gravity": 16,
  "dragon+lightning": 14,
  "demon+fire": 16,
  "gravity+earth": 20,
  "illusion+spirit": 14,
  "illusion+time": 16,
  "dragon+demon": 20,
  "light+void": 18,
  "ice+void": 16,
  "ice+shadow": 12,
  "fire+earth": 12,
  "water+wind": 10,
};

export const TITLES = [
  { id: "new", name: "New Awakening", hint: "Take your first breath in this world." },
  { id: "clan", name: "Clan Warrior", hint: "Clear wave 5." },
  { id: "elite", name: "Elite Hunter", hint: "Fell ten elite foes." },
  { id: "dragon", name: "Dragon Slayer", hint: "Defeat a dragon-class boss." },
  { id: "void", name: "Void Walker", hint: "Awaken with Void among your three." },
  { id: "chosen", name: "God's Chosen", hint: "Reach rank SSS or EX." },
  { id: "transcendent", name: "Transcendent", hint: "Raise your art to Transcendent." },
  { id: "wave20", name: "Wavebreaker", hint: "Survive wave 20." },
  { id: "untouched", name: "Untouched", hint: "Clear a wave without taking a hit." },
  { id: "hoarder", name: "Essence Hoarder", hint: "Hold 1,200 essence at once." },
  { id: "combo", name: "Flow State", hint: "Reach a 25-hit combo." },
  { id: "bosses", name: "Thronebreaker", hint: "Defeat three bosses across runs." },
] as const;

export const UPGRADE_COST = [40, 70, 110, 160, 230, 320, 430, 560, 720, 900];
export const ABILITY_UPGRADE_COST = [180, 420, 900];

export const BASE_STATS: Stats = {
  hp: 118,
  energy: 90,
  atk: 14,
  def: 8,
  spd: 168,
  crit: 8,
  power: 24,
};

export const RANK_MULT: Record<Rank, number> = {
  E: 0.86,
  D: 0.92,
  C: 1,
  B: 1.08,
  A: 1.18,
  S: 1.3,
  SS: 1.44,
  SSS: 1.62,
  EX: 1.85,
};

export const RARITY_COLOR: Record<Rarity, string> = {
  Common: "#9a958c",
  Uncommon: "#6f9a78",
  Rare: "#6a8caa",
  Epic: "#8a6a9a",
  Legendary: "#c45c4a",
  Mythic: "#d4a574",
  Divine: "#dce6ee",
  Transcendent: "#f2efe8",
};

export const RANK_COLOR: Record<Rank, string> = {
  E: "#8a8580",
  D: "#9a958c",
  C: "#c8c2b8",
  B: "#d8d2c6",
  A: "#c9b8a4",
  S: "#d4c4a0",
  SS: "#e2d4b0",
  SSS: "#eee6d6",
  EX: "#c45c4a",
};

export function xpToNext(level: number): number {
  return Math.round(80 + level * 42 + level * level * 6);
}

export function abilityTier(index: number): AbilityTier {
  return ABILITY_TIERS[Math.max(0, Math.min(ABILITY_TIERS.length - 1, index))]!;
}

export function rarityIndex(r: Rarity): number {
  return RARITIES.indexOf(r);
}

export function rankIndex(r: Rank): number {
  return RANKS.indexOf(r);
}

export function emptyUpgrades(): StatUpgrades {
  return { hp: 0, energy: 0, atk: 0, def: 0, spd: 0, crit: 0 };
}

export function computeStats(
  clanId: ClanId,
  powerIds: PowerId[],
  rank: Rank,
  level: number,
  upgrades: StatUpgrades,
  ability: UniqueAbility,
  abilityTierIndex: number,
): Stats {
  const clan = CLAN_DEFS[clanId];
  const s: Stats = { ...BASE_STATS };
  const add = (partial?: Partial<Stats>) => {
    if (!partial) return;
    (Object.keys(partial) as (keyof Stats)[]).forEach((k) => {
      s[k] += partial[k] ?? 0;
    });
  };
  add(clan.stats);
  for (const id of powerIds) {
    const p = POWER_DEFS[id];
    s.atk += p.atk;
    s.def += p.def;
    s.spd += p.spd;
    s.hp += p.hp * 3;
    s.energy += p.energy * 2;
    s.crit += p.crit;
  }
  s.hp += upgrades.hp * 14;
  s.energy += upgrades.energy * 10;
  s.atk += upgrades.atk * 3;
  s.def += upgrades.def * 2;
  s.spd += upgrades.spd * 6;
  s.crit += upgrades.crit * 2;

  const lv = 1 + (level - 1) * 0.045;
  const rm = RANK_MULT[rank];
  const tier = 1 + abilityTierIndex * 0.12;
  s.hp = Math.round(s.hp * lv * rm);
  s.energy = Math.round(s.energy * (0.92 + rm * 0.08) * (1 + abilityTierIndex * 0.04));
  s.atk = Math.round(s.atk * lv * rm * tier);
  s.def = Math.round(s.def * lv * rm);
  s.spd = Math.round(s.spd * (1 + (level - 1) * 0.012));
  s.crit = Math.min(48, Math.round(s.crit + level * 0.3 + rarityIndex(ability.rarity)));
  s.power = Math.round(ability.powerLevel * rm * tier + level * 3 + upgrades.atk * 2);
  return s;
}

export const ENEMY_KINDS = [
  "beast",
  "warrior",
  "spirit",
  "assassin",
  "drake",
  "elite",
  "miniboss",
  "boss",
  "raid",
] as const;
export type EnemyKind = (typeof ENEMY_KINDS)[number];
